Repository algovengers/Hairify, pull requests merged in 2024-05, with the labels that each got.

#49 Improved Home Page #44
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/page.tsx
  frontend/tailwind.config.ts
Labels: gssoc

#69 Loaders added for fetching chats with AI
  frontend/src/app/chat/page.tsx
Labels: gssoc, Level 1

#73 made the SignUp and the LoginPage Ui
  frontend/src/app/login/page.tsx
  frontend/src/app/signup/page.tsx
Labels: gssoc, Level 2
